name: iOS_ci

on:
  workflow_dispatch:
    inputs:
      upload-to-testflight:
        description: '上传到App Store Connect'
        required: false
        type: boolean
      upload-to-pgy:
        description: '上传到蒲公英'
        required: false
        type: boolean

jobs:
  build-ios:
    name: build
    runs-on: macos-latest
    env:
      UPLOAD_TO_TESTFLIGHT: ${{ inputs.upload-to-testflight }}
      UPLOAD_TO_PGY: ${{ inputs.upload-to-pgy }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Extract version from pubspec.yaml
        id: extract_version
        run: |
          version=$(grep '^version:' pubspec.yaml | awk '{print $2}')
          
          version_name=$(echo $version | sed 's/+.*//')
          version_code=$(echo $version | sed 's/.*+//')
          
          echo "version=$version" >> $GITHUB_ENV
          echo "version_name=$version_name" >> $GITHUB_ENV
          echo "version_code=$version_code" >> $GITHUB_ENV

      - name: Show version info
        run: |
          echo "Version: ${{ env.version }}"
          echo "Version Name: ${{ env.version_name }}"
          echo "Version Code: ${{ env.version_code }}"

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.1.app

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'

      - name: Restore packages
        run: flutter pub get

      - name: pod repo update
        run: pod repo update

      - name: flutter build ios release
        if: github.repository == 'SuperInteractica/PlantIdentification'
        uses: cedvdb/action-flutter-build-ios@v1
        with:
          build-cmd: flutter build ipa --release --export-options-plist=ios/ExportOptions.plist
          certificate-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          certificate-password: ${{ secrets.P12_PASSWORD }}
          provisioning-profile-base64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: flutter build ios test
        if: github.repository == 'Gio7/SYKJ_plant'
        uses: cedvdb/action-flutter-build-ios@v1
        with:
          build-cmd: flutter build ipa --release --export-options-plist=ios/ExportOptions.plist
          certificate-base64: ${{ secrets.P12_BASE64 }}
          certificate-password: ${{ secrets.P12_PASSWORD }}
          provisioning-profile-base64: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: Archive IPA
        uses: actions/upload-artifact@v4
        with:
          name: "plant-aab-${{ env.version_name }}_${{ env.version_code }}"
          path: build/ios/ipa/Plant Identifier.ipa

      - name: 'Upload file to test flight using CLI'
        if: env.UPLOAD_TO_TESTFLIGHT == 'true'
        run: |
          echo "Starting upload."
          xcrun altool --upload-app -t ios -f "build/ios/ipa/Plant Identifier.ipa" -u ${{ secrets.APPLE_USERNAME }} -p ${{ secrets.APPLE_PASSWORD }} --verbose

      - name: Upload PGYER File
        if: env.UPLOAD_TO_PGY == 'true'
        uses: PGYER/pgyer-upload-app-action@v1.3
        with:
          _api_key: ${{ secrets.PGY_KEY }}
          appFilePath: build/ios/ipa/Plant Identifier.ipa
          buildUpdateDescription: 'v${{ env.version_name }} (Build: ${{ env.version_code }})'
